language: cpp

compiler:
  - g++

before_install:
  - chmod +x *.sh
  - ./travis_install.sh

before_script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script: 
  - . ./build-tiles.sh
  - . ./build-anim.sh
  - . ./travis_build.sh

after_success:
  - cd ${TRAVIS_BUILD_DIR}
