language: cpp

compiler:
  - g++

matrix:
  allow_failures:
    - os: osx
  exclude:
    - os: osx
      compiler: g++

env:
  global:
    - "FTP_USER=bnsmith"

before_install:
  - chmod +x *.sh
  - ./travis_install.sh

before_script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script: 
  - ./build-tiles.sh
  - ./travis_build.sh

after_success:
  - cd ${TRAVIS_BUILD_DIR}
